---
title: "Clean User Data"
author: "gengelb"
date: "November 2, 2015"
output: html_document
---

## Clean the user data

The data were converted from *yelp_academic_dataset_user.json* to *reviews.cvs* using the jso2csv command with the following arguements.
```
json2csv -k user_id,type,name,review_count,average_stars,votes.funny,votes.useful,votes.cool,elite,yelping_since,friends  -i yelp_academic_dataset_user.json -o users.csv

{
    'type': 'user',
    'user_id': (encrypted user id),
    'name': (first name),
    'review_count': (review count),
    'average_stars': (floating point average, like 4.31),
    'votes': {(vote type): (count)},
    'friends': [(friend user_ids)],
    'elite': [(years_elite)],
    'yelping_since': (date, formatted like '2012-03'),
    'compliments': {
        (compliment_type): (num_compliments_of_this_type),
        ...
    },
    'fans': (num_fans),
}
```

The *wc -l* commands shows that there are 366715 users
```
> wc -l yelp_academic_dataset_user.json
366715 yelp_academic_dataset_user.json
> wc -l users.csv
366715 users.csv
```

### Read in the *users.csv* file.
```{r}
setwd("~/Documents/R/Capstone/final2/clean")
users <- read.csv(file="../../Analysis/data/users.csv", header=FALSE, stringsAsFactors=FALSE)

names(users) <- c("user_id", "type", "name", "review_count", "average_stars", "votes.funny", "votes.useful", "votes.cool", "elite","yelping_since","friends")

users <- users[users$review_count > 0, ]
```

### Count the friends for a reviewer
```{r}
library(stringr)

json.length <- function(list) {
  if (list == "[]") return(0)
  return(str_count(list, " ") + 1)
}

yelping.months <- function(d) {
  return(length(seq(from=as.Date(paste0(d,"-01")), to=as.Date("2015-01-01"), by="month")))
}

users$friend.count <- unlist(lapply(users$friends, json.length))
users$elite.count <- unlist(lapply(users$elite, json.length))
users$elite2015 <- ifelse(grepl("2015", users$elite), 1, 0)
users$average.votes <- round((users$votes.funny + users$votes.cool + users$votes.useful) / users$review_count, 2)
users$yelping.months <- unlist(lapply(users$yelping_since, yelping.months))
users$average.votes.funny <- round(users$votes.funny / users$review_count, 2)
users$average.votes.useful <- round(users$votes.useful / users$review_count, 2)
users$average.votes.cool <- round(users$votes.cool / users$review_count, 2)

users$friends <- NULL
users$elite <- NULL
users$type <- NULL
users$name <- NULL
users$yelping_since <- NULL
```

### Save the data set
```{r}
save(users, file="../data/users.RData")
```

